### ISSUE TITLE
Project Year not found

### ISSUE THREAD

**Issue by vastoncosta** [rafatieppo/lucylattes#1]
I'd downloaded LucyLattes yesterday and received a lot of warnings evolving project year, for all the curriculums. Warning that did not occurred before.

---------
ATENCAO 
Impossível extrair ANO para o projeto 
Interdisciplinaridade e letramentos multiplos - Subprojeto PIBID 
 do pesquisador: <nome_pesquisador>... PROJETO EXCLUIDO 

--------

Any suggestions? 

Thanks.

**Comment by rafatieppo** [comment]
Thanks for use lucyLattes.
This "warning" is a recent improvement (I guess!) :)
Several researchers do not fill Lattes CV correctly, or at times, it is a Lattes CV with old data, e.g. Projects before 1995. For this case, we usually found "issues" in the "initial year".
So a solution was implemented and warnigns are printed on the screen.

To avoid the "warnings" just fill the "initial year" for ALL projects for each Lattes CV.

Sorry about it and I hope you enjoy to use lucyLattes.
Best Regard
RT

**Comment by rafatieppo** [comment]
If you do not have questions about it I am closing this issue. Let me know about any problem.
