### ISSUE TITLE
Obrigado

### ISSUE THREAD

**Issue by RicardoMBorges** [rafatieppo/lucylattes#10]
Ola Rafael, tudo bom?
Muito Obrigado por isso. Tens alguma pretenção em continuar com atualizações e algum suporte?

Estou num Windows e instalando algumas coisas que preciso. Ainda não tenho uma pergunta de fato, mas possivelmente terei num futuro próximo.

Obrigado

**Comment by rafatieppo** [comment]
Ricardo, td blz, e vc? Pretensão eu tenho, só não consegui priorizar tempo esse ano. Quem sabe em 2024 eu consiga melhorar as coisas.Caso tenha dúvida, pode mandar que se possível tento resolver.Boa semana!



Rafael Tieppo
site: https://rafatieppo.github.io    
 

    On Tuesday, December 5, 2023 at 10:06:51 AM GMT-4, Ricardo M Borges ***@***.***> wrote:  
 
 


Ola Rafael, tudo bom?
Muito Obrigado por isso. Tens alguma pretenção em continuar com atualizações e algum suporte?

Estou num Windows e instalando algumas coisas que preciso. Ainda não tenho uma pergunta de fato, mas possivelmente terei num futuro próximo.

Obrigado

**Comment by rafatieppo** [comment]
@RicardoMBorges 

Demorou, mas saiu atualização:
- https://youtu.be/L8TFyqXlemM   (lucyLattes - instalação no Windows)
