### ISSUE TITLE
Problema na extração de dados de orientações de pós-doc

### ISSUE THREAD

**Issue by rencmbr** [rafatieppo/lucylattes#11]
Olá Rafael,

há um erro no arquivo resources/getadiv_minidom.py ao buscar o titulo da orientação concluída de pós-doc, linhas 177 a 180. Ao invés de buscar o título da orientação de pós-doc o código está buscando o título da orientação de mestrado de mesmo índice. Ou seja, essas linhas, ao invés de serem:
                    title = chd_advmaster[idx] \
                        .getElementsByTagName(
                        'DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO')[0] \
                        .getAttributeNode('TITULO').nodeValue
deveriam ser:
                   title = chd_advposdoc[idx] \
                        .getElementsByTagName(
                        'DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO')[0] \
                        .getAttributeNode('TITULO').nodeValue

Se você achar conveniente posso abrir um pull request com este conserto para o problema.

**Comment by rafatieppo** [comment]
Muito obrigado pela correção. Até ia pediar para vc abrir um pull request, mas achei mais prático altgerar p código. Fiz o commit agora pouco.Vlw



Rafael Tieppo
site: https://rafatieppo.github.io    
 

    On Tuesday, October 1, 2024 at 02:04:25 PM GMT-4, rencmbr ***@***.***> wrote:  
 
 


Olá Rafael,

há um erro no arquivo resources/getadiv_minidom.py ao buscar o titulo da orientação concluída de pós-doc, linhas 177 a 180. Ao invés de buscar o título da orientação de pós-doc o código está buscando o título da orientação de mestrado de mesmo índice. Ou seja, essas linhas, ao invés de serem:
title = chd_advmaster[idx] 
.getElementsByTagName(
'DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO')[0] 
.getAttributeNode('TITULO').nodeValue
deveriam ser:
title = chd_advposdoc[idx] 
.getElementsByTagName(
'DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO')[0] 
.getAttributeNode('TITULO').nodeValue

Se você achar conveniente posso abrir um pull request com este conserto para o problema.

**Comment by rencmbr** [comment]
Bom dia, Rafael. Creio que ainda ficou um erro na linha 177. Ao invés de: 
title = chd_advmaster[idx] 
esta linha não deveria ser
title = chd_advposdoc[idx]  ?

**Comment by rafatieppo** [comment]
Bom dia.Realmente, é isto mesmo.Obrigado pelo suporte.Vlw

Rafael Tieppo
site: https://rafatieppo.github.io    
 

    On Thursday, October 3, 2024 at 05:27:37 AM GMT-4, rencmbr ***@***.***> wrote:  
 
 


Bom dia, Rafael. Creio que ainda ficou um erro na linha 177. Ao invés de:
title = chd_advmaster[idx]
esta linha não deveria ser
title = chd_advposdoc[idx] ?
