### ISSUE TITLE
Problema de Encoding

### ISSUE THREAD

**Issue by ghost** [rafatieppo/lucylattes#2]
Olá Rafael,

Primeiramente, obrigado por seus esforços no Lucy Lattes. O projeto é incrivelmente útil e tem me ajudado demais.

No entanto, estou tendo um erro na geração do relatório que não consigo contornar. O relatório é gerado com vários símbolos nos lugares de caracteres especiais (acento, til etc.). O mesmo ocorre nos .csv dentro da pasta "relatorio". Poderia me prestar um auxílio? Estou anexando a pasta zipada do mesmo jeito que venho rodando o código. 

Abraços,

Matheus Leal
[lucylattes-master.zip](https://github.com/rafatieppo/lucylattes/files/4919673/lucylattes-master.zip)

**Comment by rafatieppo** [comment]
Para tentar resolver o problema no navegador, tente alterar as configurações do "encode". No caso do Firefox acesse:

 _Settings --> Language and Appearance - Fonts and Colors --> Advanced --> Fonts for (**Latin**)_. Se não der teste outras opções no lugar de **Latin**.

Quanto ao problema no csv, basta definir o encode no momento da importação dos arquivos.
Desculpe-me, mas infelizmente não posso ajudar mais pq tenho outras solicitações com mais prioridade no momento. 
Espero ter colaborado em suas atividades.

**Comment by rickkk856** [comment]
Outra solução é abrir o arquivo no bloco de notas e salvar com codificação UTF-8, depois disso abre normalmente no chrome e firefox...
![image](https://user-images.githubusercontent.com/62864640/114664530-36b79c00-9cd2-11eb-8172-5bc19e493fb5.png)
