### ISSUE TITLE
KeyError: 'GROUP' getgrapho()

### ISSUE THREAD

**Issue by rickkk856** [rafatieppo/lucylattes#5]
Olá, estou tentando processar os dados, e tendo problemas com o `getgrapho()`.... só está dando certo se utilizar `#getgrapho()` no arquivo `lucyLattes.py`.... será que estou configurando o grupo do jeito certo?

Já tentei configurar o grupo do `list_id_name.txt` de varios jeitos, mas o erro persiste...
Mais informações aqui : [LucyLattes - GoogleColab](https://colab.research.google.com/drive/1rUO6Wotdr1dM7LnWEZ44d86_Jei4euLc?usp=sharing) #CollabShareUpdated
 list_id_name.txt

```
# Mantenha como separador a vígula
# Não altere o nome das colunas (linha 5)
# Não altere a ordem das colunas e das 5 primeiras linhas
# Insira o nome ABREVIADO do pesquisador
ID_LATTES,NAME,GRUPO
1993723229606003,AndréAugustodeAlmeidaAlves,arq
2191256241587670,BeatrizFleuryeSilva,arq
1553616454067748,CésarImai,arq
7166105202752116,ErciliaHitomiHirota,arq
7688784916763495,FabíolaCastelodeSouzaCordovil,arq
8248534615295550,GislaineElizeteBeloto,arq
4677741821909670,HumbertoTetsuyaYamaki,arq
6702835576788945,JorgeDanieldeMeloMoura,arq
2779758207001593,JulianaHarumiSuzuki,arq
3524768907727142,KarinSchwabeMeneguetti,arq
0340067629244944,LeonardoCassimiroBarbosa,arq
3775998488185976,MarianaRagassiUrbano,arq
1179290829983998,MarieliAzoiaLukiantchuki,arq
4778641486908033,MauricioHidemiAzuma,arq
6123345863186044,MilenaKanashiro,arq
7396642409919663,RenatoLeãoRego,arq
2690327065384755,RicardoDiasSilva,arq
9399305726227880,RovenirBertolaDuarte,arq
6178824927187390,SidneiJuniorGuadanhim,arq
2371401090878231,VeraLuciaTiekoSuguihiro,arq
```
Tipo do erro:

```
KeyError: 'GROUP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lucyLattes.py", line 68, in <module>
    getgrapho()
  File "/content/lucylattes/grapho.py", line 182, in getgrapho
    lsgroup_uniq = df_idlist['GROUP'].unique()
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'GROUP'
```

**Comment by rafatieppo** [comment]
Olá bom dia.Seguinte, qual foi a data que vc fez o download do script? esses dias fiz uma correção.Caso esteja atualizado, eu nunca tive este tipo de erro, possíveis causas:
1. verifique se há espaços após o último caractere;2. tente mudar o nome de um grupo para ver o que acontece
Agora não consigo acessar o seu Colab, assim que sobrar um tempo eu vejo, inclusive acho que tem um comentário seu por no github ou um commit. Assim que der vejo tudo
Depois manda o resultado pfv.


Rafael Tieppo
site: https://rafatieppo.github.io    
 

    On Wednesday, April 14, 2021, 9:35:54 AM GMT-4, Ricardo Cesar Rodrigues ***@***.***> wrote:  
 
 


Olá, estou tentando processar os dados, e tendo problemas com o getgrapho().... só está dando certo se utilizar #getgrapho() no arquivo lucyLattes.py.... será que estou configurando o grupo do jeito certo?

Já tentei configurar o grupo do list_id_name.txt de varios jeitos, mas o erro persiste...
Mais informações aqui : LucyLattes - GoogleColab
list_id_name.txt
# Mantenha como separador a vígula
# Não altere o nome das colunas (linha 5)
# Não altere a ordem das colunas e das 5 primeiras linhas
# Insira o nome ABREVIADO do pesquisador
ID_LATTES,NAME,GRUPO
1993723229606003,AndréAugustodeAlmeidaAlves,arq
2191256241587670,BeatrizFleuryeSilva,arq
1553616454067748,CésarImai,arq
7166105202752116,ErciliaHitomiHirota,arq
7688784916763495,FabíolaCastelodeSouzaCordovil,arq
8248534615295550,GislaineElizeteBeloto,arq
4677741821909670,HumbertoTetsuyaYamaki,arq
6702835576788945,JorgeDanieldeMeloMoura,arq
2779758207001593,JulianaHarumiSuzuki,arq
3524768907727142,KarinSchwabeMeneguetti,arq
0340067629244944,LeonardoCassimiroBarbosa,arq
3775998488185976,MarianaRagassiUrbano,arq
1179290829983998,MarieliAzoiaLukiantchuki,arq
4778641486908033,MauricioHidemiAzuma,arq
6123345863186044,MilenaKanashiro,arq
7396642409919663,RenatoLeãoRego,arq
2690327065384755,RicardoDiasSilva,arq
9399305726227880,RovenirBertolaDuarte,arq
6178824927187390,SidneiJuniorGuadanhim,arq
2371401090878231,VeraLuciaTiekoSuguihiro,arq

Tipo do erro:
KeyError: 'GROUP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lucyLattes.py", line 68, in <module>
    getgrapho()
  File "/content/lucylattes/grapho.py", line 182, in getgrapho
    lsgroup_uniq = df_idlist['GROUP'].unique()
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'GROUP'

**Comment by dfrepos** [comment]
Consegui rodar seu código do Colab @rickkk856. Acho que a versão mais atualizada do git resolveu.
Por sinal, obrigado e parabéns pelo notebook. Tá muito legal. Tomei a liberdade de pegar umas partes e fazer um fork pra usar onde trabalho.

**Comment by rafatieppo** [comment]
Obrigado. Legal que está sendo útil. 
Sucesso!
