### ISSUE TITLE
Apagar pasta csv_producao

### ISSUE THREAD

**Issue by dfrepos** [rafatieppo/lucylattes#6]
Na verdade, esse post não é um issue. Apenas uma sugestão.
O @rickkk856 implementou no colab uma rotina para "resetar" a pasta csv_producao
Me pergunto se não seria interessante colocar essa rotina com as adaptações necessárias no inicio ou em algum lugar dentro do lucylattes.py.
Desta forma, toda vez que se for gerar um relatório novo, os arquivos de lá são apagados.
No entanto, não sei se tem outros aspectos que seriam afetados.

#
import os
import sys
import shutil

# Tenta apagar a pasta csv_producao
try:
    shutil.rmtree("/content/lucylattes/csv_producao")
except OSError as e:
    print ("Error: %s - %s." % (e.filename, e.strerror))

# Recria a pasta csv_produção 
%cd /content/lucylattes/
!mkdir csv_producao
#

**Comment by rafatieppo** [comment]
Obrigado. Vou anotar para melhorias futuras. Assim que eu resolver melhorar o código tentarei implementar. Só terei que fazer ajustes para sistemas linux e windows, há uma questão com o caminho dos diretórios `/` vs `\`. 
Vou fechar a issue mas sua sugestão está anotada.

**Comment by rafatieppo** [comment]
.
